# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d884020a65f992379a8fc82cdd1a11428ffb5d1b73b7d51c399db5879d923c639cfbb7d032dee2673eb7f85e3aeb36d4941c1dfb9f81787a197b468588f92992

test:
  secret_key_base: 17300448f5d62d1abe86f2a98dead179f10e76a091e5d0021fa29e969129cc7817e70b8e5e8ffeb8b912461119e22954d73db679c73cd6e8a32a4d28bf80f704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
